### ISSUE TITLE
CircleCIでテストを回す

### ISSUE THREAD

**Issue by takmnagaya** [snishizawa0509/task#12]
https://circleci.com/
ドキュメント

> https://circleci.com/docs/
> [Configuring CircleCI](https://circleci.com/docs/configuration/)
# TODO
- [x] CircleCIのアカウントを作成し、プルリク作成時やマージした際にテストが自動的に実行されるようにする。
- [x] マージされた際にHerokuに自動でデプロイできるように設定する。

**Comment by takmnagaya** [comment]
@snishizawa0509 
下記の記事を参考にGithubとHerokuの連携を設定するといいかもしれません。

> [HerokuとGitHubの連携を試してみました](http://tyoshikawa1106.hatenablog.com/entry/2015/08/12/002325)

**Comment by snishizawa0509** [comment]
https://github.com/snishizawa0509/task/pull/17
にて適応できました。

**Comment by takmnagaya** [comment]
@snishizawa0509 Herokuにデプロイされた際にidobataに通知が来るように設定してもらえますか？

**Comment by snishizawa0509** [comment]
@t-nagaya-t 
了解しました。

```
heroku addons:create deployhooks:http --url=https://idobata.io/hook/heroku/3488ddd7-cac1-471b-b6b2-92871f2efd79
```

を実行しました。

**Comment by takmnagaya** [comment]
👍

**Comment by takmnagaya** [comment]
対応いただきありがとうございました:bow:
