### ISSUE TITLE
記事の検索結果が0件の時の表示がおかしい

### ISSUE THREAD

**Issue by takmnagaya** [snishizawa0509/task#22]
`s`
![2016-07-29 16 18 52](https://cloud.githubusercontent.com/assets/14817546/17240743/3b31fc06-55a8-11e6-8284-2d665238e354.png)

**Comment by t-nagaya-t** [comment]
#19 で対応済みのためクローズ。

**Comment by takmnagaya** [comment]
間違えてクローズしてしまいました。済みません。

**Comment by snishizawa0509** [comment]
変更しました。
<img width="406" alt="2016-08-01 17 54 42" src="https://cloud.githubusercontent.com/assets/20289995/17288635/167dd13a-5811-11e6-9c03-df4f38b1fa60.png">
