### ISSUE TITLE
投稿の詳細ページでカテゴリ名が表示されない

### ISSUE THREAD

**Issue by takmnagaya** [snishizawa0509/task#6]
![2016-07-25 16 02 57](https://cloud.githubusercontent.com/assets/14817546/17093016/724906e6-5281-11e6-95d2-18d257d195b2.png)

**Comment by snishizawa0509** [comment]
修正しました。https://github.com/snishizawa0509/task/pull/7

**Comment by takmnagaya** [comment]
修正が終わったら、「close and commnet」をクリックしてissueをクローズしてもらって大丈夫です。
